- provider
- http
- shared_preferences
- intl
- flutter_bloc
- cupertino_icons
- barcode_scan
- flutter_stripe
- firebase_auth
- cloud_firestore
- flutter_local_notifications
- image_picker
- file_picker
- charts_flutter
- provider
- http
- shared_preferences
- intl
- flutter_bloc
- cupertino_icons
- barcode_scan
- flutter_stripe
- firebase_auth
- cloud_firestore
- flutter_local_notifications
- image_picker
- file_picker
- charts_flutter
- provider
- http
- shared_preferences
- intl
- flutter_bloc
- cupertino_icons
- barcode_scan
- flutter_stripe
- firebase_auth
- cloud_firestore
- flutter_local_notifications
- image_picker
- file_picker
- charts_flutter

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0         # State management
  shared_preferences: ^2.0.10  # For storing user preferences
  image_picker: ^0.8.5+3    # For picking images
  http: ^0.13.4            # For making HTTP requests
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^0.14.0
  # Add other dependencies as needed

dependencies:
  sqflite: ^2.0.2+1
  path_provider: ^2.0.11
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^0.14.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.0
  shared_preferences: ^2.0.6
  intl: ^0.17.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^0.14.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.0
  shared_preferences: ^2.0.6
  intl: ^0.17.0

flutter:
  assets:
    - assets/images/

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^0.14.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.0
  shared_preferences: ^2.0.6
  intl: ^0.17.0

flutter:
  assets:
    - assets/images/

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^0.14.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.0
  shared_preferences: ^2.0.6
  intl: ^0.17.0

flutter:
  assets:
    - assets/images/
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.10
  firebase_core: ^2.10.0
  provider: ^6.1.4
  firebase_auth: ^5.5.0
