name: aenzbi_app_flutter
description: A Flutter project for Aenzbi including multiple modules.

version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^6.0.0
  flutter_localizations:
dev_dependencies:
  flutter_test:
  build_runner: ^2.3.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/CustomFont-Regular.ttf
        - asset: assets/fonts/CustomFont-Bold.ttf
          weight: 700
# Platforms support
# Uncomment the desired platforms you want to build for
web:
  server:
    port: 8080
android:
  compileSdkVersion: 33
  targetSdkVersion: 33
ios:
  deploymentTarget: '12.0'
linux:
  extraArchitectures: []
macos:
  minimumOSVersion: '10.14'
  flutter_web_plugins: ^0.15.0  # Add this dependency for web support
  flutter_webview_plugin: ^0.14.0 # Chrome dependency for web view support
