name: aenzbi_app_flutter
description: A Flutter application for Aenzbi Business including Car Dealer System, POS functionalities, and more.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.11.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.8.0
  provider: ^6.1.5
  http: ^0.15.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  cached_network_image: ^3.2.0
  image_picker: ^0.8.7
  dio: ^5.4.0
  shared_preferences: ^2.1.0
  carousel_slider: ^4.0.0
  flutter_slidable: ^1.0.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^1.1.1
  fluttertoast: ^8.2.0
  qr_flutter: ^4.0.0
  flutter_webview_plugin: ^0.14.0
  google_fonts: ^2.3.2
  firebase_messaging: ^14.5.0
  url_launcher: ^6.0.17
  flutter_bloc: ^8.1.0
  location: ^4.4.0
  geolocator: ^9.0.0
  flutter_map: ^0.14.0
  sqflite: ^2.0.0
  get_it: ^7.2.0

# Platform-specific dependencies
flutter:
  plugin:
    platforms:
      android:
        package: com.aenzbi.app
        pluginClass: AenzbiAppPlugin
      ios:
        pluginClass: AenzbiAppPlugin
      linux:
        pluginClass: AenzbiAppPlugin
      macos:
        pluginClass: AenzbiAppPlugin
      windows:
        pluginClass: AenzbiAppPlugin
      web:
        pluginClass: AenzbiAppPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  build_web_compilers: ^3.2.0
  lint: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/data/ # Static data files if any

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
